[project]
name = "airflow-provider-sap-hana"
dynamic = ["version"]
description = "An Airflow provider to connect to SAP HANA"
requires-python = ">=3.10, <3.15"

authors = [
    { name = "Jonathan Takish", email = "jonathan.takish@gmail.com" }
]

keywords = [ "airflow", "hana", "sap hana", "sap-hana" ]
classifiers = [
    "Framework :: Apache Airflow",
    "Framework :: Apache Airflow :: Provider",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]

dependencies = [
    "apache-airflow>=3.0.6; python_version < '3.14'",
    "apache-airflow>=3.2.0; python_version == '3.14'",
    "apache-airflow-providers-common-sql>=1.27.5",
    "hdbcli>=2.26.18",
    "sqlalchemy-hana>=3.0.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-env>=1.1.5",
]
example-dag = [
    "faker>=40.23.0",
]

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[project.entry-points."apache_airflow_provider"]
provider_info = "airflow_provider_sap_hana.get_provider_info:get_provider_info"

[tool.flit.sdist]
include = ["src/airflow_provider_sap_hana"]

[tool.pytest.ini_options]
markers = ["airflow_deprecation_warning"]

## ruff settings ##
[tool.ruff]
line-length = 110
extend-exclude = [
    ".eggs",
    "*/_vendor/*",
    "airflow-core/tests/unit/dags/test_imports.py",
]

[tool.ruff.lint]
typing-modules = ["airflow.typing_compat"]


[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
combine-as-imports = true


section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
  "testing"
]

known-first-party = ["airflow"]

[tool.ruff.lint.isort.sections]
testing = ["dev", "providers.tests", "task_sdk.tests", "tests_common", "tests"]

[tool.ruff.lint.flake8-type-checking]
exempt-modules = ["typing", "typing_extensions"]

[tool.ruff.lint.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "D101", # Missing docstring in public class
    "DTZ001", # TZInfo required for datetime objects
]
